### ISSUE TITLE
Invalid CSS after "i.icon.stopwatch.": expected class name, was "20:before"

### ISSUE THREAD

**Issue by momokure** [fomantic/Fomantic-UI-SASS#11]
I tried to use Fomantic-UI-SASS and import Semantic in application.css.scss 
```
@import "semantic-ui";
```
but this error occurred.
```
Invalid CSS after "i.icon.stopwatch.": expected class name, was "20:before"
```
How can I solve this?
thanks.

**Comment by birthdaycorp** [comment]
did you manage to solve it? it's obscure

**Comment by lubber-de** [comment]
This was fixed in fomantic-ui 2.8.7 by https://github.com/fomantic/Fomantic-UI/pull/1546
This port just needs an update 😉

**Comment by birthdaycorp** [comment]
> This was fixed in fomantic-ui 2.8.7 by [fomantic/Fomantic-UI#1546](https://github.com/fomantic/Fomantic-UI/pull/1546)
> This port just needs an update 😉

thank you!! i forgot to check closed issues. i'll fork this pr and use that in my gemfile.

**Comment by birthdaycorp** [comment]
ok one final question:

in my application.css file i have this:

```
@import "semantic-ui";
/*
 *= require_self
 *= require fomantic_fixes
*/
```

those fixes are there because this gem does not allow theming. i would think that the order of import and require statements would override the default styles, but this is not the case. how would i override the default styles?

also according to [this](https://stackoverflow.com/a/39877024/2009652) compilation through `@import` takes ages, whereas with `*= require` it's pretty quick? this is definitely a thing i am realizing now that i try this out in development.

**Comment by shanecav84** [comment]
I've updated this gem to Fomantic-UI 2.8.7. Hopefully this fixes the issue.

@birthdaycorp: 

> ok one final question:
> 
> in my application.css file i have this:
> 
> ```
> @import "semantic-ui";
> /*
>  *= require_self
>  *= require fomantic_fixes
> */
> ```
> 
> those fixes are there because this gem does not allow theming. i would think that the order of import and require statements would override the default styles, but this is not the case. how would i override the default styles?
> 
> also according to [this](https://stackoverflow.com/a/39877024/2009652) compilation through `@import` takes ages, whereas with `*= require` it's pretty quick? this is definitely a thing i am realizing now that i try this out in development.

Can you open a new issue and I can take a look?
